# Generated by Django 5.0.6 on 2024-05-31 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование структурного подразделения')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Структурное подразделение',
                'verbose_name_plural': 'Структурные подразделения',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номерной знак ТС')),
                ('driving_style', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Манера вождения')),
                ('all_fines', models.IntegerField(default=0, verbose_name='Штрафы')),
                ('all_telematics_mileage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Данные телематики, пробег')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='regions.subdivision', verbose_name='Структурное подразделение')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
    ]
