# Generated by Django 5.0.6 on 2024-05-31 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_region_options_subdivision_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField(blank=True, null=True, verbose_name='Дата путевого листа')),
                ('trip_mileage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Данные путевых листов, пробег')),
                ('telematics_date', models.DateField(blank=True, null=True, verbose_name='Дата сигнала телематики')),
                ('telematics_mileage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Данные телематики, пробег')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='regions.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
            },
        ),
    ]
