# Generated by Django 5.0.6 on 2024-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='in_structure',
            field=models.BooleanField(default=False, verbose_name='В структуре парка'),
        ),
    ]
