# Generated by Django 5.0.6 on 2024-05-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_vehicle_in_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='all_true_telematics_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пробег по телеметрике'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='all_telematics_mileage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Пробег по путевым листам'),
        ),
    ]
