# Generated by Django 5.0.6 on 2024-06-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_vehicle_all_true_telematics_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='text_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='Анализ структурного подразделения'),
        ),
    ]
